---
- name: Install oVirt API dependences
  host: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Install dependences to connect to the oVirt API
      apt:
        name:
          - python3-pip
          - libcurl4-openssl-dev
          - libxml2-dev
          - libssl-dev
        state: present

    - name: Install oVirt API Python SDK
      pip:
        name: ovirt-engine-sdk-python
        version: 4.4.0
        state: present